GET http://localhost:8083/api/activities
Authorization: Basic 1

###
GET http://localhost:8083/api/activities/7
Authorization: Basic 1

###
POST http://localhost:8083/api/activities
Content-Type: application/json
Authorization: Basic 1

{
  "name": "Test Activity",
  "kcalPerMinute": 7.0
}

###
DELETE http://localhost:8083/api/activities/5
Authorization: Basic 1
